<a href="https://colab.research.google.com/github/yousee0/D.Heart/blob/master/Seaborn%2C_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy array 생성하기**

In [2]:
import numpy as np
data = np.random.randint(10, size=(10,10))
print(data)

[[2 6 8 6 0 6 8 3 3 5]
 [9 9 4 1 1 3 8 8 6 9]
 [8 8 1 6 8 2 8 8 9 3]
 [7 4 1 9 7 6 0 7 9 2]
 [9 2 1 5 8 4 0 2 6 4]
 [7 7 4 7 8 1 2 0 4 5]
 [1 8 7 9 8 9 5 0 0 7]
 [8 8 0 5 9 0 2 3 0 3]
 [2 4 0 0 4 1 3 0 4 6]
 [5 8 8 8 9 8 3 1 7 6]]


**seaborn 라이브러리 사용하여 array 배열하기**